server:
  port: 8762

eureka:
  instance:
    hostname: registry2
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      #defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://registry1:8761/eureka/,http://registry3:8763/eureka/
    #fetch-registry: true
    #register-with-eureka: true
security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
