

spring:
  application:
    name: svcb-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      username: user
      password: ${CONFIG_SERVER_PASSWORD:password}
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
feign:
  hystrix:
    enabled: true  #feign集成hystrix需要配置开启
#management:
#  security:
#    enabled: false

#endpoints:
#  refresh:
#    enabled: true